// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace MWGameplayTags
{
	MW_API	FGameplayTag FindTagByString(const FString& TagString, bool bMatchPartialString = false);

#pragma region ActionTag
	// Default Input
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Debug);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_Move);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_LookAt);
	//MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_Look_Stick);
	//MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_Crouch);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_AutoRun);

	// Battle Command
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_BC_Move);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_BC_ChangeLeader);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_BC_UseItem);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_BC_UseSpirit);

	// Combat Command
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_CC_Attack_Up);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_CC_Attack_Down);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_CC_Attack_Left);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_CC_Attack_Right);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_CC_Dir_Up);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_CC_Dir_Down);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_CC_Dir_Left);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_CC_Dir_Right);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_CC_SupportAttack1);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_CC_SupportAttack2);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IATag_CC_UltimateSkill);
#pragma endregion

#pragma region InputMappingTag
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IMCTag_Basic);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IMCTag_BattleCommand);
	MW_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(IMCTag_CombatCommand);
#pragma endregion
};
